### ISSUE TITLE
TypeError: gofileApiwrapper is not a constructor

### ISSUE THREAD

**Issue by TheBaconPug** [404ProgramNotFound/apiWrap-Gofile#3]
```js
const api = new gofileApiwrapper(process.env.EMAIL, process.env.TOKEN);
```

**Comment by 404ProgramNotFound** [comment]
ye i miss spelled it in the documentation  the proper way to call it is 
`
const gofileApiwrapper = require('gofile-apiwrapper');
var api = new gofileApiwrapper.apiGofile("email","apitoken");
`
